version: 2.1
jobs: 
    lint:
        docker: 
            - image: cimg/python:3.8
        steps:
            - checkout
            - run : 
                name : install dependencies
                command: |
                    pip install pymysql
            - run : 
                name: install linting libraries
                command: |
                    pip install pylint
                    pip install cfn-lint
            - run : 
                name: lint python codes
                command: |
                    pylint --variable-naming-style camelCase LambdaPackageGetCurrentPI/lambda_function.py
                    pylint --variable-naming-style camelCase LambdaPackageUpdateCurrentPI/lambda_function.py
            - run: 
                name: lint cloudformation template
                command: |
                    cfn-lint SQS-LambdaStack.json
    zipPythonPackages:
        docker:
            - image: cimg/base:stable-20.04
        steps:
            - checkout
            - run: 
                name: update packages
                command: |
                    sudo apt-get update
                   # sudo apt-get -y upgrade
            - run:
                name: zip packages
                command: |
                    mkdir zip
                    cd zip
                    zip -r LambdaPackageUpdateCurrentPI.zip ../LambdaPackageUpdateCurrentPI
                    zip -r LambdaPackageGetCurrentPI.zip ../LambdaPackageGetCurrentPI
                    ls -l
            - save_cache:
                key: ubuntu-cache
                paths: [zip]
            - persist_to_workspace: 
                root : zip
                paths:
                    - LambdaPackageGetCurrentPI.zip
                    - LambdaPackageUpdateCurrentPI.zip
    uploadZipsToS3:
        docker:
            - image: amazon/aws-cli
        steps:
            - attach_to_workspace: 
                at: /zip
            - run:
                name: test
                command: |
                    cd zip
                    ls





workflows: 
    testflow: 
        jobs: 
            #- lint
            - zipPythonPackages
            #    requires: 
            #        - lint
            - uploadZipsToS3:
                requires: 
                    - zipPythonPackages
