version: 2.1
jobs: 
    lint:
        docker: 
            - image: cimg/python:3.8
        steps:
            - checkout
            - run : 
                name : install dependencies
                command: |
                    pip install pymysql
            - run : 
                name: install linting libraries
                command: |
                    pip install pylint
                    pip install cfn-lint
            - run : 
                name: lint python codes
                command: |
                    pylint --variable-naming-style camelCase LambdaPackageGetCurrentPI/lambda_function.py
                    pylint --variable-naming-style camelCase LambdaPackageUpdateCurrentPI/lambda_function.py
            - run: 
                name: lint cloudformation template
                command: |
                    cfn-lint SQS-LambdaStack.json
    zipPythonPackages:
        docker:
            - image: cimg/base:stable-20.04
        steps:
            - checkout
            - restore-cache:
                keys: [ubuntu-cache]
            - run: 
                name: update packages
                command: |
                    sudo apt-get update
                    sudo apt-get -y upgrade
            - run: 
                name: install zip
                command: |
                    sudo apt-get install zip
            - run:
                name: zip packages
                command: |
                    mkdir zip
                    zip -r zip/LambdaPackageUpdateCurrentPI.zip LambdaPackageUpdateCurrentPI
                    zip -r zip/LambdaPackageGetCurrentPI.zip LambdaPackageGetCurrentPI
            - save_cache:
                key: ubuntu-cache
                paths: [/]
            - persist_to_workspace: 
                root : .circleci/zip
                paths:
                    - ./LambdaPackageGetCurrentPI.zip
                    - ./LambdaPackageUpdateCurrentPI.zip


workflows: 
    testflow: 
        jobs: 
            - lint
            - zipPythonPackages:
                requires: 
                    - lint
