version: 2.1
jobs: 
    lint:
        docker: 
            - image: cimg/python:3.8
        steps:
            - checkout
            - run : 
                name : install dependencies
                command: |
                    pip install pymysql
            - run : 
                name: install linting libraries
                command: |
                    pip install pylint
                    pip install cfn-lint
            - run : 
                name: lint python codes
                command: |
                    pylint --variable-naming-style camelCase LambdaPackageGetCurrentPI/lambda_function.py
                    pylint --variable-naming-style camelCase LambdaPackageUpdateCurrentPI/lambda_function.py
            - run: 
                name: lint cloudformation template
                command: |
                    cfn-lint SQS-LambdaStack.json


workflows: 
    testflow: 
        jobs: 
            - lint
