version: 2.1
jobs: 
    lint:
        docker: 
            - image: cimg/python:3.8
        steps:
            - checkout
            - run : 
                name: install linting library
                command: |
                    pip install pylint
                    pip install cfn-lint

workflows: 
    testflow: 
        jobs: 
            - lint
