version: 2.1
jobs: 
    lint:
        docker: 
            - image: cimg/python:3.8
        steps:
            - checkout
            - run : 
                name: install linting libraries
                command: |
                    pip install pylint
                    pip install cfn-lint
            - run : 
                name: lint python codes
                command: |
                    ls
                    pylint --variable-naming-style camel_case LambdaPackageGetCurrentPI/lambda_function.py
                    pylint --variable-naming-style camel_case LambdaPackageUpdateCurrentPI/lambda_function.py

workflows: 
    testflow: 
        jobs: 
            - lint
