version: 2.1
jobs: 
    lint:
        docker: 
            - image: cimg/python:3.8
        steps:
            - checkout
            - run : 
                name : install dependencies
                command: |
                    pip install pymysql
            - run : 
                name: install linting libraries
                command: |
                    pip install pylint
                    pip install cfn-lint
            - run : 
                name: lint python codes
                command: |
                    pylint --variable-naming-style camelCase LambdaPackageGetCurrentPI/lambda_function.py
                    pylint --variable-naming-style camelCase LambdaPackageUpdateCurrentPI/lambda_function.py
            - run: 
                name: lint cloudformation template
                command: |
                    cfn-lint SQS-LambdaStack.json
    zipPythonPackages:
        docker:
            - image: cimg/base:stable-20.04
        steps:
            - checkout
            - run: 
                name: update packages
                command: |
                    sudo apt-get update
                   # sudo apt-get -y upgrade
            - run:
                name: zip packages
                command: |
                    mkdir zip
                    cd zip
                    zip -r LambdaPackageUpdateCurrentPI-"`date +"%d-%m"`".zip ../LambdaPackageUpdateCurrentPI
                    zip -r LambdaPackageGetCurrentPI-"`date +"%d-%m"`".zip ../LambdaPackageGetCurrentPI
                    ls -l
            - save_cache:
                key: ubuntu-cache
                paths: [zip]
            - persist_to_workspace: 
                root : zip
                paths:
                    - '*'
    uploadZipsToS3:
        docker:
            - image: amazon/aws-cli
        steps:
            - run:
                name: tar gzip
                command: |
                    yum -y install tar gzip
            - attach_workspace: 
                at: .circleci/python_packages
            - run:
                name: upload zip files to s3
                command: |
                    aws s3 cp .circleci/python_packages/LambdaPackageGetCurrentPI-"`date +"%d-%m"`".zip s3://generalfilesbackfit
                    aws s3 cp .circleci/python_packages/LambdaPackageUpdateCurrentPI-"`date +"%d-%m"`".zip s3://generalfilesbackfit
    createOrUpdateStack:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                name: tar gzip
                command: |
                    yum -y install tar gzip
            - run: 
                name: create variables
                command: |
                    S3KEYTOSQSENV=LambdaPackageGetCurrentPI-"`date +"%d-%m"`".zip
                    S3KEYFROMSQSENV=LambdaPackageUpdateCurrentPI-"`date +"%d-%m"`".zip
                    echo $S3KEYTOSQSENV
                    echo $S3KEYFROMSQSENV

            - run:
                name: update stack
                command: |
                    echo $S3KEYFROMSQSENV
                    aws cloudformation deploy --template-file SQS-LambdaStack.json \
                     --stack-name PIBalanceUpdate --capabilities CAPABILITY_NAMED_IAM \
                     --parameter-overrides RDSHOST=${RDS_HOST} RDSDB=${RDS_DB} \
                     RDSUSER=${RDS_USER} RDSPASSWORD=${RDS_PASSWORD} \ 
                     S3KEYTOSQS=$S3KEYTOSQSENV \
                     S3KEYFROMSQS=$S3KEYFROMSQSENV




workflows: 
    launchPiCaseBalanceUpdate: 
        jobs: 
            #- lint
            #- zipPythonPackages:
            #    requires: 
            #        - lint
            #- uploadZipsToS3:
            #    requires: 
            #        - zipPythonPackages
            - createOrUpdateStack
            #    requires:   
            #        - uploadZipsToS3
